name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [master]}
  # Run this workflow once per day, at 10:15 UTC
  schedule: [{cron: "0 0 15 * *"}]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: {}

env: 
  CDSAPIKEY: ${{ secrets.CDSAPIKEY }}
  OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - name: build environment
        run: |
          python -m pip install cdsapi datetime netCDF4 pandas python-dotenv
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to Observable Cloud
        # This parameter to `--message` will use the latest commit message
        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
